# Generated by Django 5.0.3 on 2024-06-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.organization'),
        ),
        migrations.AddField(
            model_name='donate',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.organization'),
        ),
        migrations.AddField(
            model_name='sponsertable',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.organization'),
        ),
    ]
