# Generated by Django 5.0.3 on 2024-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_adoptionrequest_organization_donate_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
