# Generated by Django 5.0.3 on 2024-06-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_customuser_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdetails',
            name='image',
            field=models.ImageField(default=1, upload_to='child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childdetails',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.organization'),
        ),
    ]
