# Generated by Django 5.0.3 on 2024-06-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_childdetails_image_childdetails_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='childdetails',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
