# Generated by Django 5.0.6 on 2024-06-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_adoptionrequest_additional_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='isapproved',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
