# Generated by Django 5.0.6 on 2024-06-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0008_remove_adoptionrequest_isapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], max_length=50, null=True),
        ),
    ]
