# Generated by Django 5.0.6 on 2024-07-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0009_alter_adoptionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChildAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
            ],
        ),
    ]
