# Generated by Django 5.0.6 on 2024-07-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0010_alter_adoptionrequest_status_childappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childappointment',
            old_name='Child',
            new_name='child',
        ),
    ]
