# Generated by Django 5.0.6 on 2024-07-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0012_alter_customuser_user_type_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food_and_nutrition', 'Food and Nutrition')], default='medical', max_length=50),
        ),
    ]
