# Generated by Django 5.0.6 on 2024-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0013_donation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
