# Generated by Django 5.0.6 on 2024-07-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0014_donation_order_id_donation_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
