# Generated by Django 5.0.6 on 2024-07-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0015_donation_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponserShipApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food_and_nutrition', 'Food and Nutrition')], max_length=20, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails')),
            ],
        ),
    ]
