# Generated by Django 5.0.6 on 2024-07-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0016_sponsershipapplicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsershipapplicants',
            name='sponsor_type',
        ),
        migrations.AddField(
            model_name='sponsershipapplicants',
            name='sponsor_category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food_and_nutrition', 'Food and Nutrition')], max_length=20, null=True),
        ),
    ]
