# Generated by Django 5.0.6 on 2024-07-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0017_remove_sponsershipapplicants_sponsor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsershipapplicants',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
