# Generated by Django 5.0.6 on 2024-07-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0018_sponsershipapplicants_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsershipapplicants',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
