# Generated by Django 5.0.6 on 2024-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0019_sponsershipapplicants_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsershipapplicants',
            name='amount',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
