# Generated by Django 5.0.6 on 2024-07-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0020_alter_sponsershipapplicants_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeTimeSponserShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails')),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
            ],
        ),
    ]
