# Generated by Django 5.0.6 on 2024-07-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0021_lifetimesponsership'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeTimeSponserShipNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food_and_nutrition', 'Food and Nutrition')], max_length=20, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('lifeTimesponserShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.lifetimesponsership')),
            ],
        ),
    ]
