# Generated by Django 5.0.6 on 2024-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0022_lifetimesponsershipneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetimesponsershipneeds',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
