# Generated by Django 5.0.7 on 2024-07-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0023_lifetimesponsershipneeds_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conformchild',
            name='child',
        ),
        migrations.RemoveField(
            model_name='conformchild',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='sponsertable',
            name='child',
        ),
        migrations.RemoveField(
            model_name='sponsertable',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sponsertable',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdoptionFormView',
        ),
        migrations.DeleteModel(
            name='ConformChild',
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.DeleteModel(
            name='SponserTable',
        ),
    ]
