# Generated by Django 6.0.1 on 2026-03-12 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0024_remove_conformchild_child_remove_conformchild_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails'),
        ),
    ]
