# Generated by Django 6.0.1 on 2026-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0025_adoptionrequest_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
